# .github/workflows/ticket_checker.yml
name: UZ Ticket Checker

on:
  workflow_dispatch: # Дозволяє запускати вручну з вкладки Actions
  schedule:
    # Запускає скрипт кожні 15 хвилин.
    # УВАГА: часті запити можуть тимчасово заблокувати ваш IP з боку УЗ.
    # 15-30 хвилин - оптимальний інтервал.
    - cron: '*/15 * * * *'

jobs:
  check-tickets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run ticket checker script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_tickets.py
